Initialization
initializeNamed: aName withLogo: aLogo mapLocation: aPoint described: aDescription webSite: aWebsite serviceTime: aCollection deliveryLocation: anotherLocation with: aContactInformation

	name := aName.
	logo := aLogo.
	mapLocation := aPoint.
	description := aDescription.
	webSite := aWebsite.
	serviceTime := aCollection.
	deliveryLocation := anotherLocation.
	contactInformation := aContactInformation.
	scores := OrderedCollection new