Accessing
synchronizeWith: anUpdatedFoodBusiness
	
	logo := anUpdatedFoodBusiness logo.
	location := anUpdatedFoodBusiness location.
	address := anUpdatedFoodBusiness address.
	mapLocation := anUpdatedFoodBusiness mapLocation.
	description := anUpdatedFoodBusiness description.
	webSite := anUpdatedFoodBusiness webSite.
	email := anUpdatedFoodBusiness email.
	phoneNumber := anUpdatedFoodBusiness phone.
	serviceTime := anUpdatedFoodBusiness serviceTime.
	deliveryLocation := anUpdatedFoodBusiness deliveryLocation.