Initialization
initializeNamed: aName withLogo: aLogo locationAt: aLocation address: anAddress mapLocation: aPoint described: aDescription webSite: aWebsite email: anEmail phone: aPhoneNumber serviceTime: aCollection deliveryLocation: anotherLocation 
	name:= aName.
	logo := aLogo.
	location := aLocation.
	address := anAddress .
	mapLocation := aPoint .
	description := aDescription .
	website := aWebsite .
	email := anEmail  .
	phone := aPhoneNumber .
	serviceTime := aCollection .
	deliveryLocation := anotherLocation 