tests
testInstanceCreationFailedBecauseMinimumQuantityPriceIsHigherThanPrice
	self
		should: [ FoodMenu
				named: 'McCombo'
				description: 'Burguer + fries and coke'
				categories: categories
				deliveryValue: 10
				validDatePeriod: {((Monday to: Friday) -> (8 to: 20))} asDictionary
				deliveryTimePeriod: {((Monday to: Friday) -> (8 to: 20))} asDictionary
				deliveryTimeAverage: 60
				price: 30
				minimumQuantity: 40
				minimumQuantityPrice: 50
				minimumQuantity2: 71
				minimumQuantityPrice2: 0
				maximumSaleQuantity: 200 ]
		raise: InstanceCreationFailed
		withExceptionDo: [ :exception | 
			self
				assert: exception messageText
				equals: 'El precio debe ser mayor al precio de la cantidad mínima' ]