FoodBusiness-Config
classModelFoodBusiness: aModel
	aModel
		newAttributeNamed: #id;
		newAttributeNamed: #name;
		newAttributeNamed: #logo;
		newAttributeNamed: #location;
		newAttributeNamed: #address;
		newAttributeNamed: #mapLocation;
		newAttributeNamed: #description;
		newAttributeNamed: #webSite;
		newAttributeNamed: #email;
		newAttributeNamed: #phoneNumber;
		newAttributeNamed: #serviceTime;
		newAttributeNamed: #deliveryLocation;
		newAttributeNamed: #scores