initialization
initializeName: aName description: aDescription categories: manyCategories deliveryValue: aValue validDatePeriod: aPeriod deliveryTimePeriod: aDeliveryPeriod deliveryTimeAverage: aTimeAverage price: aPrice minimumQuantity: aMinimumQuantity minimumQuantityPrice: aMinimumQuantityPrice minimumQuantity2: anotherMinimumQuantity minimumQuantityPrice2: anotherMinimumQuantityPrice maximumSaleQuantity: aMaximumSaleQuantity.

name := aName.
description := aDescription.
categories := manyCategories.
deliveryValue := aValue.
validDatePeriod := aPeriod.
deliveryTimePeriod := aDeliveryPeriod.
deliveryTimeAverage := aTimeAverage.
price := aPrice.
minimumQuantity := aMinimumQuantity.
minimumQuantityPrice := aMinimumQuantityPrice.
minimumQuantity2 := anotherMinimumQuantity.
minimumQuantityPrice2 := anotherMinimumQuantityPrice.
maximumSaleQuantity := aMaximumSaleQuantity.  