Initialization
initializeName: aName description: aDescription categories: manyCategories deliveryValue: aValue datePeriod: aPeriod deliveryTimePeriod: aDeliveryPeriod deliveryTimeAverage: aTimeAverage price: aPrice minQuantity: aMinimumQuantity minQuantityPrice: aMinimumQuantityPrice minQuantity2: anotherMinimumQuantity minQuantityPrice2: anotherMinimumQuantityPrice maxSaleQuantity: aMaximumSaleQuantity

	name := aName.
	description := aDescription.
	categories := manyCategories.
	deliveryValue := aValue.
	validDatePeriod := aPeriod.
	deliveryTimePeriod := aDeliveryPeriod.
	deliveryTimeAverage := aTimeAverage.
	price := aPrice.
	minimumQuantity := aMinimumQuantity.
	minimumQuantityPrice := aMinimumQuantityPrice.
	minimumQuantity2 := anotherMinimumQuantity.
	minimumQuantityPrice2 := anotherMinimumQuantityPrice.
	maximumSaleQuantity := aMaximumSaleQuantity