Updating
synchronizeWith: aFoodMenu

name := aFoodMenu menuName.
description := aFoodMenu description.
categories := aFoodMenu categories.
deliveryValue := aFoodMenu deliveryValue.
validDatePeriod := aFoodMenu validDatePeriod.
deliveryTimePeriod := aFoodMenu deliveryTimePeriod.
deliveryTimeAverage := aFoodMenu deliveryTimeAverage.
price := aFoodMenu price.
minimumQuantity := aFoodMenu minimumQuantity.
minimumQuantityPrice := aFoodMenu minimumQuantityPrice.
minimumQuantity2 := aFoodMenu minimumQuantity2.
minimumQuantityPrice2 := aFoodMenu minimumQuantityPrice2.
maximumSaleQuantity := aFoodMenu maximumSaleQuantity.